version: '3.8'
services:
  db:
    image: postgres:15
    container_name: vulnprint_db
    environment:
      POSTGRES_USER: vulnuser
      POSTGRES_PASSWORD: vulnpassword
      POSTGRES_DB: vulnprint
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: vulnprint_mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Port

volumes:
  pgdata:
